### ISSUE TITLE
Suggest UseBasicParsing when used on clients where IE is not initalised

### ISSUE THREAD

**Issue by aaron-ccrfs** [baswijdenes/Optimized.Mga.SharePoint#1]
https://github.com/baswijdenes/Optimized.Mga.SharePoint/blob/8b2ad54d0e339eee7fe0bfaf6466b24a929e390e/Optimized.Mga.SharePoint.psm1#L109

Have been playing around using your module with Azure DevOps and windows hosted agents. As the IE instance isn't interactive since it's never been opened, you get the error:

```bash
the response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. 
```

Putting -UseBasicParsing removes this requirement as suggested and it works perfectly. Not sure if its something you want to consider for compatibility since the full IE engine isn't required?

**Comment by baswijdenes** [comment]
Hey, I fully agree with you and will add this to the To-Do list! Thanks in advance

**Comment by baswijdenes** [comment]
I've updated the module both here & in the PowerShell gallery.
Thank you for your feedback!
