### ISSUE TITLE
Upload-MgaSharePointFiles function not exposed/exported

### ISSUE THREAD

**Issue by envegter** [baswijdenes/Optimized.Mga.SharePoint#2]
Hello Bas, congrats on this module and thanks for publishing it! 
I installed the module and noticed that the Upload-MgaSharePointFiles function is not exported. I used the PSM1 file as PS1 file and dot-sourced it to use all functions and the upload function seems to work as desired.

Best regards,
Eric

**Comment by baswijdenes** [comment]
Ha good find! Thank you for reporting this ;-) I updated it immediately! (both in Github and PSgallery)
